apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
#  ownerReferences:
#  - apiVersion: hive.openshift.io/v1
#    kind: ClusterDeployment
#    name: {{ .Release.Name }}
#    uid: TODO
spec:
  clusterDeploymentRef:
    name: {{ .Release.Name }}
  holdInstallation: true
  imageSetRef:
    name: {{ .Values.imageSetRefName }}
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
  provisionRequirements:
    controlPlaneAgents: {{ .Values.controlPlaneAgents }}
