apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.pullSecretB64 }}
kind: Secret
metadata:
  name: pullsecret-cluster-{{ .Release.Name }}
  namespace: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
